const WeatherIcons = [
  { idx: 1, icon: require('./1-s.png') },
  { idx: 2, icon: require('./2-s.png') },
  { idx: 3, icon: require('./3-s.png') },
  { idx: 4, icon: require('./4-s.png') },
  { idx: 5, icon: require('./5-s.png') },
  { idx: 6, icon: require('./6-s.png') },
  { idx: 7, icon: require('./7-s.png') },
  { idx: 8, icon: require('./8-s.png') },
  { idx: 11, icon: require('./11-s.png') },
  { idx: 12, icon: require('./12-s.png') },
  { idx: 13, icon: require('./13-s.png') },
  { idx: 14, icon: require('./14-s.png') },
  { idx: 15, icon: require('./15-s.png') },
  { idx: 16, icon: require('./16-s.png') },
  { idx: 17, icon: require('./17-s.png') },
  { idx: 18, icon: require('./18-s.png') },
  { idx: 19, icon: require('./19-s.png') },
  { idx: 20, icon: require('./20-s.png') },
  { idx: 21, icon: require('./21-s.png') },
  { idx: 22, icon: require('./22-s.png') },
  { idx: 23, icon: require('./23-s.png') },
  { idx: 24, icon: require('./24-s.png') },
  { idx: 25, icon: require('./25-s.png') },
  { idx: 26, icon: require('./26-s.png') },
  { idx: 29, icon: require('./29-s.png') },
  { idx: 30, icon: require('./30-s.png') },
  { idx: 31, icon: require('./31-s.png') },
  { idx: 32, icon: require('./32-s.png') },
  { idx: 33, icon: require('./33-s.png') },
  { idx: 34, icon: require('./34-s.png') },
  { idx: 35, icon: require('./35-s.png') },
  { idx: 36, icon: require('./36-s.png') },
  { idx: 37, icon: require('./37-s.png') },
  { idx: 38, icon: require('./38-s.png') },
  { idx: 39, icon: require('./39-s.png') },
  { idx: 40, icon: require('./40-s.png') },
  { idx: 41, icon: require('./41-s.png') },
  { idx: 42, icon: require('./42-s.png') },
  { idx: 43, icon: require('./43-s.png') },
  { idx: 44, icon: require('./44-s.png') },
];

export default WeatherIcons;
